# Generated by Django 5.0.6 on 2024-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(max_length=200)),
                ('app_contant', models.TextField(max_length=200)),
                ('app_image', models.ImageField(blank=True, upload_to='images/')),
                ('app_date', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.TextField(max_length=200)),
                ('co_email', models.CharField(max_length=200)),
                ('co_message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.TextField(max_length=200)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
