# Generated by Django 5.0.6 on 2024-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=200)),
            ],
        ),
    ]
