# Generated by Django 5.0.6 on 2024-07-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0002_switch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='switch',
            new_name='Todo',
        ),
    ]
