# Generated by Django 5.0.6 on 2024-07-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0003_rename_switch_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
